### ISSUE TITLE
Transaction doesn't save and order status isn't updated

### ISSUE THREAD

**Issue by JulienDotDev** [quadra-informatique/Magento-Module-Paybox#6]
hi,
i'm using the lastest version of your module with a magento community ver. 1.5.1.0.

I reach the paybox payment platform but when i come back to my succes page, in my BO there is anything new in my order except the message in my history "customer back from paybox success".

I have entries in the Paybox Api Debug section but nothing really relevent for me :/ 

Ty

**Comment by mpasquin** [comment]
Hello,

Do you use a self-signed ssl certificate?
Paybox payment platform verifies if the ssl certificate is valid. If the certificate is self-signed then the payment server doen't send the payment response to your server and orders stay in pending state.

Regards.

**Comment by JulienDotDev** [comment]
Hi,

well it wasn't about the ssl certificate. I did those tests in a private environement so i did got the data from the redirect but not from paybox sending data asynchronously to magento (thoses data didn't reached magento in the private space).

Sry for my bad english skills.
